junegunn/fzf.vim

autoload/fzf/vim.vim
Since fzf will execute the source command in the tagfile's directory, we
can't give the path of the tagfile relative to the current working
directory. Instead give just the filename.
=> Fix :Tags command tagfile relative path

plugin/fzf.vim
Thought this looked nicer in NeoVim and gives it a more distinguished separation.
Before
After
=> Replace the terminal window's statusline in NeoVim

README.md, autoload/fzf/vim.vim, doc/fzf-vim.txt
In my environment '--graph' is a kiss of death. It results in seeing
nothing but graph lines due to the number of branches in the environment.
Secondly the colors baked into this break with my color scheme
which has a background of black rending the date unreadable.
I pulled it out as an option to just specify the command. This might be too flexible but it was an easy solution for me.  I just add to my ``.vimrc``:
```
let g:fzf_commit_log_command = 'git log --color=always --format="%C(auto)%h%d %s %C(blue)%C(bold)%cr"'
```
=> Pull out the git log command as an option

autoload/fzf/vim.vim
Added ability to specify the commands used to generate tags
Some filetypes have better tag generators than ctags. For example, Javascript has jsctags which found all the functions in a file while ctags found 4.
This change lets you set the BTags command to use whatever commands you want to generate tags.
```
autocmd FileType javascript command! -buffer BTags
\ call fzf#vim#buffer_tags([
\ printf('jsctags %s -f', expand('%:S')),], {})
```
These changes are based on https://github.com/junegunn/fzf.vim/commit/0ad88dd4e8136e7eed48c27937a1f55efe0bc69c
=> fzf#vim#buffer_tags([tag commands], options)

README.md, autoload/fzf/vim.vim, doc/fzf-vim.txt, plugin/fzf.vim
This pull request introduces a new command that allows you to search through the various valid file types.
It essentially fixes the issue I created here: https://github.com/junegunn/fzf.vim/issues/109.
=> Add `Filetypes` command.

autoload/fzf/vim.vim
terribly small change, but pulls all neovim terminal files from the history file search via pattern `term://`
=> add neovim terminal files to history filter

autoload/fzf/vim.vim
This should fix color selection with true-color enabled terminal neovim.
=> Make sure to use the cterm color attribute

autoload/fzf/vim.vim
Hi there! 
There's a small bug in FZFLines that prevents jumping to line found in another buffer. I've removed the slicing and now it works ok.
=> removed unneeded slice

autoload/fzf/vim.vim, autoload/fzf/vim/complete.vim
This has been broken in 397a2e6.
=> Fix fzf#vim#complete#line with new bufname display

autoload/fzf/vim.vim
With 'nowrapscan' a tag might not be found, depending of the position in
the file.
=> [vim] handle 'nowrapscan' option in s:tags_sink

autoload/fzf/vim.vim
`systemlist` doesn't exist in older versions of Vim. See jebaum/vim-tmuxify#18
=> [GitFiles] Use system instead of systemlist

autoload/fzf/vim.vim
By default git-status won't include new files in new directories.
E.g.
foo/bar/baz.txt # "baz.txt" is a new file in a new directory "bar".
$ git status --short
?? foo/bar/
=> [GFiles?] include all untracked files

autoload/fzf/vim.vim
Some plugins sometimes mess up with buffer names and so they become absolute.
This makes searching for buffers with fzf harder. This commit fixes that by
formatting buffers relatively to the cwd so fzf always get relative buffer
names.
=> [Buffers] Force formatting buffers relative to current dir

autoload/fzf/vim.vim
This is a fairly tiny change.
It simply redirects the ctags error to /dev/null in case the current project contains some files which create errors with ctags.
=> ctags redirects 2>/dev/null

plugin/fzf.vim
Tiny change. Allows users to set the styling on the fzf1, fzf2, and fzf3 highlight groups.
=> Allow restyling of the fzf[123] groups

autoload/fzf/vim.vim
This makes it work more intuitively with plugins like [flazz/vim-colorschemes](https://github.com/flazz/vim-colorschemes).
=> [fzf#vim#colors] Remove duplicate colorschemes

autoload/fzf/vim.vim
Somehow the tags file generated by ctags for the linux kernel, tag
v4.10-rc1 contains non-ASCII characters. grep stops when it detects
non-ASCII characters. This patch adds the -a option to the grep command
to treat the tags file as ASCII text.
Steps to reproduce:
```
$ git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
$ cd linux
$ git checkout v4.10-rc1
$ make O=. SRCARCH=x86 tags
$ grep -v '^!' tags | tail
Binary file tags matches
```
Another possibility is to call grep with `LC_ALL=C`.
(Fixes #5)
=> fix :Tags by adding -a option to grep

plugin/fzf.vim
if i defined commands start with `Ag`. (e.g. [1]) fzf.vim can't define `:Ag` command.
[1]: `command! AgGem call fzf#vim#ag(<q-args>)`
=> when checking exists of commands it checks full match

autoload/fzf/vim.vim
Initial work for  #410.
I added `s:merge_opts` to handle `eopts` so it can fallback to string options.
I didn't use `fzf#shellescape` so it work in Window only if `g:fzf_files_options` is unset or a list.
Maybe it's better to not support string values for these user options in Windows.
=> [Files] runs in Windows

autoload/fzf/vim.vim
This is the first time I've ever written VimL, so I'm sure there's a better way to do it. But this seems to achieve what we were looking for in https://github.com/junegunn/fzf.vim/issues/367 :) @junegunn do you think excluding the current file would be a good idea in general?
=> exclude the current file from History

autoload/fzf/vim.vim
Need https://github.com/junegunn/fzf/pull/1021 for the backslash queries
`s:q` uses `fzf#shellescape` now but `Tags` and `BTags` use `s:q`.
What do you think of removing/reworking `s:q` and use list type for options?
=> [Lines,BLines,Buffers] works in Windows

autoload/fzf/vim.vim
It works with relative paths only.
`s:open` is not using `fnameescape`.
=> [Tags, BTags] works in Windows

autoload/fzf/vim.vim
Resolves https://github.com/junegunn/fzf.vim/pull/427#issuecomment-323584383
Supports the absolute filepaths generated by `ctags -R --output-format=e-ctags --tag-relative=never`
=> [Tags] support Windows-style absolute filepaths

autoload/fzf/vim.vim
It should work with the preview because ag does not output the network drive but the absolute filepath of the preview script must be modified with `fnamemodify` and  either `set shellslash` or `escape(abspath, '\')` to get around escaping issues.
Ideally, `s:fzf` should return early if running on windows, the preview script is used and if there is either no source or `FZF_DEFAULT_COMMAND` is undefined such that fzf defaults to `dir /s/b`.
=> [Ag, fzf#vim#grep] works in Windows

autoload/fzf/vim.vim, autoload/fzf/vim/complete.vim, plugin/fzf.vim
Aside from `<plug>(fzf-complete-word)`, all of the other `<plug>`  are okay.
I used double quotes for `<plug>(fzf-complete-file-ag)` because single quotes for empty pattern doesn't work for ag in cmd.exe
Tested only in Vim and GVim.
For some reason, mappings don't work anymore in Neovim on Windows.
=> [fzf#vim#complete#path] works in Windows

autoload/fzf/vim.vim, bin/preview.sh
Ruby script doesn't work with cmd.exe in the terminal if the script is run in a batchfile.
I don't know how to preview the file in a batchfile or powershell so bash script is the only option. I adjusted the bash script to handle the network drive such that it works with `dir /s/b`.
=> [fzf#vim#preview] works with Windows default command

autoload/fzf/vim.vim, bin/preview.rb
Close #459
Requires 0.17.1
This re-enables the ruby preview script if ruby is available in PATH. The changes is a port of the fix for Windows' network drive in the bash preview script.
=> [fzf#vim#preview] Use ruby in Windows if available

autoload/fzf/vim.vim
This PR removes the `--graph` flag when only listing commits for the current buffer.
Given that the list of commits for the given buffer are not generally contiguous in the git tree, the graph fragments rendered don't make much sense.
Additionally, git will also output lines of `...` , which the FZF preview trips up over, and appears to render the diff back from `HEAD`. This is particularly frustrating in larger repositories, when only a fraction of commits affect the current buffer.
Before: _(showing nonsensical preview)_
```
vim.vim
BCommits>   < 281/281 +S                           ┌────────────────────────────────────────────────┐
:: Press CTRL-S to toggle sort, CTRL-D to diff   │ diff --git a/autoload/fzf/vim.vim b/autoload/f │
* 19df93a (HEAD -> bcommits, mine/bcommits) do.. │ index …
```
=> Don't attempt to render disparate chunks of commit graph in :BCommits

autoload/fzf/vim.vim
The vim help recommends putting colorschemes below `pack/*/opt`, so fzf.vim should search for them there too.
=> [fzf#vim#colors] Pick up colorschemes from opt packages

autoload/fzf/vim.vim
This should crudely filter out files that are listed multiple times in `git ls-files` because of the state they're in (e.g. during a rebase).
Perhaps there is a better way to achieve this? I'm afraid I'm not very familiar with the internals of `fzf` / `fzf.vim`.
Thanks,
Josh
=> Avoid duplicate entries in :GFiles

autoload/fzf/vim.vim
By default git will quote filenames that contain special characters.
From the git help on the `core.quotepath` config:
> The commands that output paths (e.g. `ls-files`, `diff`), when not given
> the `-z` option, will quote "unusual" characters in the pathname by
> enclosing the pathname in a double-quote pair and with backslashes the
> same way strings in C source code are quoted. If this variable is set
> to false, the bytes higher than 0x80 are not quoted but output as
> verbatim. Note that double quote, backslash and control characters are
> always quoted without `-z` regardless of the setting of this variable.
This quoting behaviour means that GitFiles cannot be used to open files
that contain any special characters. Fix this by using the `-z` option
to `ls-files` together with the …
=> [GitFiles] Support files with special characters

autoload/fzf/vim.vim
First commit: prefer echo to pipe over redirect (fixes the bug mentioned in the title)
Second commit: [B]Commit preview will fail if the commit message has another long string of numbers such as a tracker story id, etc. This limits the output of grep to select the first match (which will be the commit hash, or nothing at all)
=> [B]Commit preview fails if using fish shell

autoload/fzf/vim.vim
Close: https://github.com/junegunn/fzf.vim/issues/553
This should allow Windows users to not require associating `pl` file extension with perl and avoid opening notepad.exe (default behaviour).
Personally, I don't need it because I use the installer from http://strawberryperl.com/ but msysgit comes with perl.exe already.
=> [Tags] run perl for s:bin.tags

autoload/fzf/vim.vim
Related: https://github.com/junegunn/fzf.vim/pull/493
Close: https://github.com/junegunn/fzf.vim/issues/554
=> [fzf#vim#with_preview] Escape preview script path

autoload/fzf/vim.vim
Related: https://github.com/neovim/neovim/issues/7788
On Vim, it's `ruby path\\to\\bin\\preview.rb`.
On Neovim, it's `ruby > path\\to\\bin\\preview.rb`
The patch reduces the output to a single line so the extra newline doesn't affect `s:bin.preview`.
=> [fzf#vim#with_preview] workaround system() newline on Neovim

autoload/fzf/vim.vim
If `tags` is set in the `wildignore` option, `:Helptags` command would
always return an empty list.
The proposed fix is to ignore `wildignore` on the `globpath` call.
=> Fix Helptags command

README.md
Do this so it matches the ~official :GFiles
You are of course welcome to decline this change.  I just found this much more useful.  I fooled around a little bit with actually moving this into the plugin proper, but my vimscript abilities weren't quite up to the job.
=> Change :GGrep example to work at project level.

autoload/fzf/vim.vim
`s:q()` is removed and `--query` is included directly in the options list.
Tested with latest version on Windows 8.1 and Ubuntu 16.04
=> [Tags][Lines][Buffers] use list type for options

autoload/fzf/vim.vim
This is nice for (ab)using :BTags to "browse" functions in a source file.
I assume `--sort=no` was used for performance, but on a single file maybe that doesn't matter?
=> buffer_tags: sort tags

autoload/fzf/vim.vim
Issue: While following paths in a file, it might end up in paths like
`a/b/../c/d.ext` or `a/b/./c.ext`, which would be cleaner if displayed
like `a/c/d.ext` and `a/b/c.ext`.
Solution: Expand fullpath to resolve directories before collapsing it to
home directory/relative path.
=> Clean up buffer names in :Buffers

autoload/fzf/vim.vim
Commits:
1. common function to fill quickfix, since it's called in several places in the file
2. BLines accepts `--multi` and can build quickfix
3. BLines query isn't inserted in the fzf window, but it's used to prefilter lines
Quickfix for BLines allows `:cdo`.
With commit 3. you can do things like:
```
BLines {{{[0-9]
```
to filter foldmarkers.
In general, having `query` work as a prefilter allows to filter fzf list with some other text (much more freely that is), and it's also treated as a regex.
=> function to fill quickfix, some changes to BLines

autoload/fzf/vim.vim
Actually I would want the unfold to only happen, if the matched line is really hidden within a fold. In the current version of the PR, the fold will also be unfolded when the matched line is the beginning of the fold. Unfortunately, I did not find any way to tell, if the current line is hidden within a fold.
=> Unfold after Lines/BLines

README.md, autoload/fzf/vim.vim, bin/preview.rb, bin/preview.sh
[bat](https://github.com/sharkdp/bat) is a very nice clone of `cat` that supports syntax highlighting feature. If bat is available, one may want to have it as a syntax highlighter used in `preview.sh` or `preview.rb`. This PR adds the support.
I have implemented the functionality to be close to what `preview.sh` is doing, with `awk`. Of course, the use of `bat` is absolutely optional. It allows us to have a syntax highlighting feature even without ruby.
Another note: it might conflict with #707.
=> Support bat for syntax highlighting in preview

bin/preview.sh
This wasn't working on NixOS due to bash not being under `/bin`. Using `env` should make it compatible with more setups.
=> Use `env` to get `bash`

autoload/fzf/vim.vim
Use `{count}tabnext` instead of `normal {count}gt` to avoid error that cannot re-enter normal mode in terminal mode in neovim.
=> Use `{count}tabnext` instead of `normal {count}gt`

autoload/fzf/vim.vim
I have `;` and `:` swapped in my vimrc, so using the `:Commands` command is broken because `feedkeys` uses my remapped `:`. This PR tells `feedkeys` to not remap keys for the `:Commands` sink function.
=> Do not remap keys when using feedkeys

doc/fzf-vim.txt
The first field on the first line of a help file should be a link to the help file name. (See :h help-writing)
=> Allow 'fzf-vim.txt' to be listed in the LOCAL ADDITIONS section of help.txt

autoload/fzf/vim.vim
If there's an autocmd for BufReadPost that jumps to the last position,
searching for the tag location sometimes results in vim printing the
wrapscan warning and then requires hit-enter. Jump to the beginning
before searching for the tag to ensure consistent (no hit-enter)
behaviour.
=> Workaround for last-position-jump in :Tags

autoload/fzf/vim.vim
Added `'n'` (to not remap keys) argument to `feedkeys` function.
I personally have `:` key remapped and `ctrl-e` doesn't work correctly for `:History:`.
=> Bugfix: editing a command from history when colon is remapped

bin/preview.sh
Fixes outstanding comments in #774 and #890.
=> Fix preview of paths starting with ~/

autoload/fzf/vim.vim
Opening files with a double-colon results in wrong filename getting used for opening the file.
The fix is pretty naive and static, it replaces all double-colon with another (less-used) character and so far works only for exactly two repeating colons (i tried to make it a regex but it didn't work, i'm a vimscript rookie)
=> (bugfix) filenames with double-colons will lead to erroneous behaviour

autoload/fzf/vim.vim
If file in buffer is located in submodule then bcommit doesn't show the history of this file.
fixes: https://github.com/junegunn/fzf.vim/issues/918
=> Add support for files in submodules when using BCommits/Commits

bin/preview.sh
since fzf v0.18.0 `FZF_PREVIEW_LINES` is preferred over `LINES`.
See this issue junegunn/fzf/issues/1314 and this commit junegunn/fzf@8dc1377efb140c40c7e121b29d9cedb52ad9ea9f
=> Use FZF_PREVIEW_LINES instead of LINES

bin/preview.sh
I use `bin/preview.sh` in my shell script outside of vim. When I'm previewing, I want to also show the filename at the top of the preview window. Luckily, `bat` has already provideded such feature, like using `--style="numbers,header"`.  Although I can add `--style="numbers,header"` to `~/.config/bat/config`, but `bat --style=numbers ...` in `bin/preiew.sh` will win over that. So I propose to append  `FZF_PREVIEW_BAT_OPTIONS` to the command in `bin/preiew.sh`, so anyone who is using bat to preview can pass in extra options to override specified options.
Does this make sense? Thanks.
=> Respect BAT_STYLE in bin/preview.sh

bin/preview.sh
The regex is supposed to replace tilde to $HOME.
However the regex used unnecessary escaping, so the replacing was
mistaken.
The path always showed "File not found" in preview window.
```bash
FILE='~/work/test.sh'
FILE_before_fix="${FILE/#\~\//$HOME\/}"
echo $FILE_before_fix
FILE_after_fix="${FILE/#\~\//$HOME/}"
echo $FILE_after_fix
```
=> Fix(preview.sh): Fix Regex that replace tilde in wrong way

README.md, autoload/fzf/vim.vim, doc/fzf-vim.txt, plugin/fzf.vim
Before this patch, a search pattern starting with a dash like
`:Rg -bang` would fail (or exhibit the wrong behaviour) because it would
be treated as a option. However, this case is very common when searching
for ->member in a project in C, C++, PHP, etc.
=> use -- before the search pattern for Ag, Rg, etc.

autoload/fzf/vim.vim
Rename and make `s:all_files` public for user fzf extensions? (See #1013 for context and use case example.)
=> Rename and make `s:all_files` public for user fzf extension?

autoload/fzf/vim.vim
Temporary perl script that parses output of help grep doesn't take into account backward slash as windows path separator.
Fixes #987
=> fix: Helptags doesn't work on Windows

autoload/fzf/vim.vim
Function `ag_to_qf` is used to parse line produced by Grep, Ag or
Ripgrep. Implementation in quesition split it using regexp that doesn't
work for windows absolut paths.
A better approach is to use `matchlist` function.
Fixes #1037
=> fix: Handle absolute windows paths in Grep/Ag/Ripgrep sink process

autoload/fzf/vim.vim
Hi!
I really enjoy this plugin. I just wrote a customization to the `:Buffers` command I shared at https://github.com/junegunn/fzf/wiki/Examples-(vim)#delete-buffers-from-buffers and this requires these small changes. I hope it'll be OK with you.
Regards.
=> Expose some buffer related functions

bin/preview.sh
Seemed to me this is neater then changing it manually, or having to create a symlink, which isn't necessarily possible when user has installed the alternative bat package.
Additionally/alternatively a vimrc option could also be created to define path/name of executable of bat.
=> Incorporate batcat name

autoload/fzf/vim.vim, bin/preview.sh
Fixes #1212 by 
- setting MSWINHOME environment variable (to calculated $HOME from vim)
- exports these to WSL (if needed)
- using MSWINHOME in preview.sh for ~
- translating Windows path to WSL path
=> Preview support for MS Windows (WSL and Git bash) - Fixes #1212

bin/tagpreview.sh
The `tagpreview.sh` script is hardcoded to the `vim` binary. For users that only
have  Neovim installed an error is displayed and no preview is rendered.
This change addresses this by falling back to the `nvim` binary if the `vim`
binary isn't present.
Addresses #1261
=> Use nvim if vim not installed

autoload/fzf/vim.vim
I tried to add this to my dotfiles:
```vim
let s:fzf_files_opts = {
\ 'window': {'width': 0.6, 'height': 0.6, 'relative': v:false},
\ 'options': ['--layout=reverse', '--info=inline'],
\}
command! -bang -nargs=? -complete=dir Files   call fzf#vim#files(<q-args>, s:fzf_files_opts, <bang>0)
```
Now, probably not the best way to customize FZF, but please bear with me. The intention here is to use `--layout=reverse` to have the input at the top, instead of the bottom. Works the first time I try it, but subsequent tries move it back to the bottom.
The bottom line is that `fzf#vim#files()` ends up mutating its argument when calling `s:fzf`. It gets fixed by making a defensive copy.
=> Don't mutate args to fzf#vim#files() (and other)

autoload/fzf/vim.vim, plugin/fzf.vim
In 161da95, [B]Commits were changed to range commands with -range=%, now
Vim jumps to the first line when these two commands are called directly
without specifying range.
This fixes it by saving window view in a temporary variable and
restoring it later. Reference: [1].
[1] https://vi.stackexchange.com/a/6037/33583
=> [[B]Commits] Preserve window view

autoload/fzf/vim.vim
Fix #1320
Append fzf argument `--no-unicode` when ambiwidth is `double` to keep the preview window rendering correctly.
=> [preview] Support for ambiwidth=double

.gitattributes
Otherwise on Windows it may cause preview.sh to have CRLF as line endings and fail to preview.
=> Ensure bash scripts to always use unix line endings

autoload/fzf/vim.vim, plugin/fzf.vim
This PR adds a preview window to the vim help searcher.
+ In `fzf#vim#helptags`, we now also parse out the ex-command in the perl script so it's available for the preview (this is just an extra `\t(.*)` appended to the original regex).
+ Add the `--tag` placeholder to `:Helptags` with corresponding arguments.
And a beautiful screenshot of it in action : )
=> [Helptags] add preview window to :Helptags command

autoload/fzf/vim.vim
Hello!
I've been a long time user of vim+`fzf` on Windows.
I have always had an issue with the previews on `GFiles?` on Windows:
I figured that:
* the pipes are not properly escaped in my use cases (one computer using `bash` from `wsl` (Windows), another computer using `bash` from the installation directory of `git` (Windows))
* `bash` cannot find the `preview` script if its path has backwards slashes
Today I took the time to make a PR.
I did not see Contribution guidelines so I am opening this PR directly.
Please tell me if you need a ticket, additional information, or anything that could help you with this PR.
Best regards,
Melandel.
=> [GFiles?] Fix preview on windows (wsl bash + git_install_folder/usr/bash)

autoload/fzf/vim.vim
Since https://github.com/junegunn/fzf//commit/85ae7459103c3aeef39383d8c8a4fbbdb9fb5f64,
fzf opens in a terminal buffer (in my setup) and that breaks commands
that end up showing the hit-enter or more prompt, such as :scriptnames
or :ALEInfo. No idea why those commands break (I tried to diagnose this
but gave up unfortunately), but executing them using feedkeys fixes
this.
=> [Commands] Fix hit-enter/more-prompt with terminal buffer fzf

autoload/fzf/vim.vim
With some delta configurations (e.g. color-only = true, diff-highlight =
true), delta doesn't add its own coloring and keeps that from git diff,
and thus we need to turn that on.
Additionally, delta doesn't do its own detection of moved lines and
relies on git diff's colorMoved, which also needs enabling of colors.
=> [[B]Commits] Use --color=always with delta as well

autoload/fzf/vim/complete.vim
related: https://github.com/junegunn/fzf.vim/issues/1029
fzf could respect dictionary option by a few changes. And fzf will maintain the behavior of the previous version if user don't have dictionary option by default.
=> [fzf#vim#complete#word]: respect dictionary option

autoload/fzf/vim.vim
git ls-files quotes file names containing "unusual" (non-ASCII?) characters by default, breaking :GFiles
=> make :GFiles work with "unusual" filenames

autoload/fzf/vim.vim
Because of a quirk of the nushell syntax, it doesn't allow programs surrounded in quotes to be executed, as they are interpreted as string objects. I fixed this issue by making `bash` call the script.
=> Add support for nushell

autoload/fzf/vim.vim
The commit linked below removed `a:args` from the `git ls-files` command, making it unable to take any options like `--cached`, `--others` and `--exclude-standard`
https://github.com/junegunn/fzf.vim/commit/531dd67350331771c0c099e9682a05744149e7b9
=> fix: GFiles is ignoring args

README.md, autoload/fzf/vim.vim, bin/preview.sh, doc/fzf-vim.txt
Fix preview window problems for Windows user.
I generally use Arch for development, but recently I also started using WSL, sometimes I don't want to open WSL, so I just open nvim in terminal and use it, I'm kind of a heavy user of `fzf.vim`, this plugin is really good. However, I found that the preview window reported various errors when using it directly in Windows (e.g. `nvim-qt`); 
I looked through the documentation and some other PRs, but I found that some of the solutions could cause another problem while solving one, so I tried to fix some of the problems and added an option to use other bash directly ( git bash, for example).
I've tried to minimize the impact on users using other environments, and I use WSL and Linux myself, so I understand the importance of stability.
Here's what …
=> Fix: Windows preview window logic, including git diff preview

README.md, autoload/fzf/vim.vim, doc/fzf-vim.txt, plugin/fzf.vim
This PR adds the `:Jumps` command, working in a similar fashion to `:Marks`.
=> add :Jumps

autoload/fzf/vim.vim
This removes fzf#vim#helptags dependencies on external "grep" and "sort" commands. I think it also makes the code simpler. The special filename handling for Windows could be removed.
I put the removal of the external "sort" in a separate commit since it can affect the sort order. E.g. my Windows "sort" command puts single-quote (') before bang (!), while Perl's sort does the reverse. (Perl sorts these in ASCII order.)
Note that this does not make :Helptags fully work for me on Windows. There is one further problem: preview.sh is called with colons as separators for the filenames, etc., which breaks on Windows. I fixed it locally but I'm not sure what a good universal separating character other than colon could be. I used '$' locally but that may not be a good choice for Linux users.
=> Remove dependencies of :Helptags on grep and sort to make it easier to get it working on Windows

bin/tagpreview.sh
When computing the center line, if the file is open the vim command returns with a non-zero exit code and the `return` is executed. This yields a weird error message "return: can only `return'" in the preview window, even if the preview is properly displayed
=> tagpreview: open vim in readonly mode

autoload/fzf/vim.vim
When working in large repositories, 9 characters can be ambiguous.
Bumping it to 40, which is the length of SHA-1. (The algorithm is not
that relevant though. Even when SHA-256 takes over, 40 characters should
still be enough for most repositories.)
=> [[B]Commits] Bump Git commit hash length limit to 40

autoload/fzf/vim.vim
Follow-up to 832a090870a79d8be87d8856c821806512a45b23.
=> Use s:conf for preview_bash and files_options

autoload/fzf/vim.vim
Reduce the preview of :BCommits to the relevant part, when used with visual selection. Only show the part of the diff that belongs to the selection.
That makes it very easy to quickly follow the evolution of a code block. I've used this feature over two month now, and it proved to be super useful.
=> Improve :BCommits Preview

autoload/fzf/vim.vim
This PR:
1) Adds scoop_git_bash to windows bash candidates. Scoop installs git for windows at ~/scoop/apps/git/current and sets the environment variable to $GIT_INSTALL_ROOT to this path.
2) Prioritizes Windows' bash over wsl bash. WSL bash causes errors for many reasons, some of which include:
- wsl bash may exist on the $PATH but not be installed
- wsl may not be started (which *may* cause an error)
- wsl cannot start due to hyper-v being disabled
Tested successfully on:
- vim + Git Bash / mintty
- nvim + cmd
nvim + Git Bash doesn't work and hasn't worked for quite a while.
=> add scoop_git_bash to windows bash candidates

autoload/fzf/vim.vim
This fix would allow nvim in cmd / powershell to use scoop_git_bash instead of wsl bash.
It should have been included in #3809.
=> fix environment variable reference in #3809

README.md, autoload/fzf/vim.vim
Display PATH:LINE:COL on a separate line for narrow screens. Requires Perl and fzf 0.53.0 (not yet released).
* See https://github.com/junegunn/fzf/pull/3807
```vim
" [Ag|Rg|RG] Display path on a separate line for narrow screens (default: 0)
" * Requires Perl and fzf 0.53.0 or later
let g:fzf_vim.grep_multi_line = 0
" PATH:LINE:COL:LINE
let g:fzf_vim.grep_multi_line = 1
" PATH:LINE:COL:
" LINE
let g:fzf_vim.grep_multi_line = 2
" PATH:LINE:COL:
" LINE
" (empty line)
```
=> [fzf#vim#grep / Ag / Rg / RG] Multi-line display for narrow screens

autoload/fzf/vim.vim
This aims too fix an issue expressed over here:
https://github.com/junegunn/fzf/issues/3188
Instead of going with the fix attempt over here:
https://github.com/junegunn/fzf/pull/4264
From what I can tell, only git commands are broken in the setting where `&shell=pwsh` and it's because of the escaping of characters in the path. In pwsh, you only need to quote a string and the path should be resolved correctly.
=> autoload/fzf: get_git_root, wrap system call with fzf#with_sh

autoload/fzf/vim.vim
fzf uses `normal! m'` for some reason. There's a known issue regarding `normal` usage in neovim. See
https://github.com/neovim/neovim/issues/4895 for more details
As a temporary (yeah, right) workaround, use setpos to set the bookmark instead.
=> Add workaround for `normal!` bug in nvim terminals
