junegunn/fzf.vim

- README.md
- doc/fzf-vim.txt
- plugin/fzf.vim
> Command history and search history (#6)

- autoload/fzf/vim.vim
This also uses --tabstop=1 explicitly, where the default of 8 would add
too much whitespace - especially with another tabstop being used to
split the line number from the buffer name.
What do you think?
> lines: display buffer names if there are more than 100 columns

- autoload/fzf/vim.vim
This uses `--` to separate the file name.
> Fix GitFiles? for deleted files

- README.md
- doc/fzf-vim.txt
This should be XDG compliant and keeps the user's home dir clean.
> doc: suggest better default for g:fzf_history_dir

- autoload/fzf/vim.vim
> Use fugitive (if available) to get the git root

- autoload/fzf/vim.vim
- bin/preview.sh
I don't use ruby, but would still like to enjoy the fzf preview feature.
This adds a preview.sh script as a bare-bones alternative to preview.rb
for those without ruby installed.
> add preview.sh for ruby-less previews.

- autoload/fzf/vim.vim
- plugin/fzf.vim
This works just like how :Lines does, except I also allow it to
autocomplete based on buffers.
> Allow :Buffers to take a query argument

- bin/preview.rb
https://github.com/jneen/rouge
> Add support for the rouge highlighter.

- autoload/fzf/vim.vim
Moved the perl script to a temporary file (don't know when to delete it) to avoid escaping issues.
Not sure about the filepath regex to resolve the network drive but it does the job
> [Helptags] works in Windows

- autoload/fzf/vim.vim
Initial work for `GFiles?` in Windows.
The preview command hasn't changed but Windows doesn't have the required tools by default.
> [GFiles?] works in Windows

- autoload/fzf/vim.vim
Works only in `s:execute` of fzf's Vim plugin.
`s:execute_term` corrupts the output of `fzf#shellescape`.
> [Commits,BCommits] works in Windows

- autoload/fzf/vim.vim
Port of junegunn/fzf/pull/1043
> [Files] do not pathshorten prompt in cygwin

- autoload/fzf/vim.vim
> Revert "[GitFiles] Support files with special characters"

- autoload/fzf/vim.vim
Port of https://github.com/junegunn/fzf/commit/7727ad43afb57cb325439590a9a6bad94601a720
Close #504
> [Tags] Use fnameescape to escape command line arguments

- README.md
- doc/fzf-vim.txt
Is now consistent with Ag. And more convenient
> Smart case for rg (readme)

- bin/preview.rb
- bin/preview.sh
First al all, thank so much @junegunn for your awesome contributions, keep it up!
I would like to see the symbolic links in the preview
I hope to be useful
> Fix preview of symbolic links

- README.md
> Fix broken anchor in link

- README.md
- doc/fzf-vim.txt
> Remove useless line in autocmd

- autoload/fzf/vim.vim
Change to address https://github.com/junegunn/fzf.vim/issues/997
> #997 Extract filename and line number for maps comment

- autoload/fzf/vim.vim
Close https://github.com/junegunn/fzf.vim/issues/988
Close https://github.com/junegunn/fzf.vim/pull/1009
@ladevieq Please review.
> [fzf#vim#with_preview] support wsl bash

- bin/preview.sh
> Preview fails when the file name or path contains the binary keyword

- autoload/fzf/vim.vim
Close https://github.com/junegunn/fzf.vim/issues/1052
@vyasr Can you test?
> [fzf#vim#with_preview] Detect WSL bash on Windows only

- autoload/fzf/vim.vim
after running into #591 myself I created the fix, following the patter in c3954d294a0f6c4fb5a46a1839cd42ec26767dea. 
manual test seems fine for me.
> [Tags] unfold after Tags/BTags

- autoload/fzf/vim.vim
The ".." Lua operator has sneaked in here, causing invalid expression errors... :)
> Concat string with "."

- bin/tagpreview.sh
This commit fixes GitHub issue #1228.
> [Tagpreview] Handle absolute file paths correctly

- autoload/fzf/vim.vim
> Show current file first in (B)Commits preview

- autoload/fzf/vim.vim
This is similar to #1218, with some extra work to make it functional in
.git directory as well.
It's been quite useful to me when I need to work in a parent directory
of multiple repositories.
> Automatically change Git working directory according to current buffer

- README.md
- autoload/fzf/vim.vim
- autoload/fzf/vim/complete.vim
- doc/fzf-vim.txt
- plugin/fzf.vim
Hi @junegunn, your code is exceptionally well-written. It's evident that you've put a lot of thought and effort into it. I'm particularly impressed by the clean and efficient structure you've created. The readability and organization make it a pleasure to work with. however, I have a small suggestion to enhance it even further. considering the way to work with external program, `fzf#shellescape` is better
> Use fzf#shellescape instead

- doc/fzf-vim.txt
I assume this is not intentional as the doc file is a regular txt file. I see this in fzf repo as well.
> Replace unicode figure space (U+2007) with regular space

- .github/ISSUE_TEMPLATE.md
- README.md
- autoload/fzf/vim.vim
- bin/preview.sh
- doc/fzf-vim.txt
- plugin/fzf.vim
> Jumps support preview window
